package model.enums;

import java.util.ArrayList;

public enum EItem {
	
	//Blocks
	stone(1,0,"stone",EItemCat.block),
	grass(0,0,null,null),
	dirt(0,0,null,null),
	cobblestone(0,0,null,null),
	oakplank(0,0,null,null),
	redplank(0,0,null,null),
	birchplank(0,0,null,null),
	jungleplank(0,0,null,null),
	oaksapling(0,0,null,null),
	redsapling(0,0,null,null),
	birchsapling(0,0,null,null),
	junglesapling(0,0,null,null),
	sand(0,0,null,null),
	gravel(0,0,null,null),
	goldore(0,0,null,null),
	ironore(0,0,null,null),
	coalore(0,0,null,null),
	oakwood(0,0,null,null),
	redwood(0,0,null,null),
	birchwood(0,0,null,null),
	junglewood(0,0,null,null),
	oakleaf(0,0,null,null),
	redleaf(0,0,null,null),
	birchleaf(0,0,null,null),
	jungleleaf(0,0,null,null),
	glass(0,0,null,null),
	lapisore(0,0,null,null),
	lapisblock(0,0,null,null),
	dropper(0,0,null,null),
	sandstone(0,0,null,null),
	sandstonechiseled(0,0,null,null),
	sandstonesmooth(0,0,null,null),
	noteblock(0,0,null,null),
	poweredrail(0,0,null,null),
	pressrail(0,0,null,null),
	pistonstick(0,0,null,null),
	cobweb(0,0,null,null),
	grasstall(0,0,null,null),
	fern(0,0,null,null),
	deadbush(0,0,null,null),
	piston(0,0,null,null),
	woolwhite(0,0,null,null),
	woolorange(0,0,null,null),
	woolmagenta(0,0,null,null),
	woollblue(0,0,null,null),
	woolyellow(0,0,null,null),
	woollgreen(0,0,null,null),
	woolpink(0,0,null,null),
	woolgray(0,0,null,null),
	woollgray(0,0,null,null),
	woolcyan(0,0,null,null),
	woolpurple(0,0,null,null),
	woolblue(0,0,null,null),
	woolbrown(0,0,null,null),
	woolgreen(0,0,null,null),
	woolred(0,0,null,null),
	woolblack(0,0,null,null),
	floweryellow(0,0,null,null),
	flowerred(0,0,null,null),
	mushbrown(0,0,null,null),
	mushred(0,0,null,null),
	goldblock(0,0,null,null),
	ironblock(0,0,null,null),
	stoneslab(0,0,null,null),
	sandslab(0,0,null,null),
	cobbleslab(0,0,null,null),
	brickslab(0,0,null,null),
	stonebrickslab(0,0,null,null),
	netherbrickslab(0,0,null,null),
	quartzslab(0,0,null,null),
	brickblock(0,0,null,null),
	tnt(0,0,null,null),
	bookshelf(0,0,null,null),
	mossstone(0,0,null,null),
	obsidian(0,0,null,null),
	torch(0,0,null,null),
	oakstair(0,0,null,null),
	chest(0,0,null,null),
	diamondore(0,0,null,null),
	diamondblock(0,0,null,null),
	workbench(0,0,null,null),
	furnace(0,0,null,null),
	ladder(0,0,null,null),
	rail(0,0,null,null),
	stonestair(0,0,null,null),
	lever(0,0,null,null),
	stonepressure(0,0,null,null),
	woodpressure(0,0,null,null),
	redstoneore(0,0,null,null),
	redstonetorch(0,0,null,null),
	button(0,0,null,null),
	snowlay(0,0,null,null),
	ice(0,0,null,null),
	snowblock(0,0,null,null),
	cactus(0,0,null,null),
	clayblock(0,0,null,null),
	jukebox(0,0,null,null),
	woodfence(0,0,null,null),
	pumpkin(0,0,null,null),
	netherrack(0,0,null,null),
	soulsand(0,0,null,null),
	glowstoneblock(0,0,null,null),
	jackolantern(0,0,null,null),
	trapdoor(0,0,null,null),
	stonebrick(0,0,null,null),
	mosstonebrick(0,0,null,null),
	crackstonebrick(0,0,null,null),
	chisstonebrick(0,0,null,null),
	mushblock1(0,0,null,null),
	mushblock2(0,0,null,null),
	ironbar(0,0,null,null),
	glasspane(0,0,null,null),
	melonblock(0,0,null,null),
	vine(0,0,null,null),
	fencegate(0,0,null,null),
	brickstair(0,0,null,null),
	stonebrickstair(0,0,null,null),
	mycelium(0,0,null,null),
	lilypad(0,0,null,null),
	netherbrick(0,0,null,null),
	netherfence(0,0,null,null),
	netherbrickstair(0,0,null,null),
	enchanttable(0,0,null,null),
	endstone(0,0,null,null),
	enderegg(0,0,null,null),
	redstonelampoff(0,0,null,null),
	redzstonelampon(0,0,null,null),
	oakslab(0,0,null,null),
	redslab(0,0,null,null),
	birchslab(0,0,null,null),
	jungleslab(0,0,null,null),
	sandstair(0,0,null,null),
	emeraldore(0,0,null,null),
	enderchest(0,0,null,null),
	hook(0,0,null,null),
	emeraldblock(0,0,null,null),
	redstair(0,0,null,null),
	birchstair(0,0,null,null),
	junglestair(0,0,null,null),
	beacon(0,0,null,null),
	cobblewall(0,0,null,null),
	mosscobblewall(0,0,null,null),
	woodbutton(0,0,null,null),
	anvil(0,0,null,null),
	anvilmid(0,0,null,null),
	anvilbad(0,0,null,null),
	trapchest(0,0,null,null),
	goldpressure(0,0,null,null),
	ironpressure(0,0,null,null),
	lightdetector(0,0,null,null),
	redstoneblock(0,0,null,null),
	quartzore(0,0,null,null),
	hopper(0,0,null,null),
	quartzblock(0,0,null,null),
	chisquartzblock(0,0,null,null),
	pillarquartzblock(0,0,null,null),
	quartzstair(0,0,null,null),
	activatorrail(0,0,null,null),
	dispenser(0,0,null,null),
	stainedclaywhite(0,0,null,null),
	stainedclayorange(0,0,null,null),
	stainedclaymagenta(0,0,null,null),
	stainedclaylblue(0,0,null,null),
	stainedclayyellow(0,0,null,null),
	stainedclaylgreen(0,0,null,null),
	stainedclaypink(0,0,null,null),
	stainedclaygray(0,0,null,null),
	stainedclaylgray(0,0,null,null),
	stainedclaycyan(0,0,null,null),
	stainedclaypurple(0,0,null,null),
	stainedclayblue(0,0,null,null),
	stainedclaybrown(0,0,null,null),
	stainedclaygreen(0,0,null,null),
	stainedclayred(0,0,null,null),
	stainedclayblack(0,0,null,null),
	hayblock(0,0,null,null),
	carpetwhite(0,0,null,null),
	carpetorange(0,0,null,null),
	carpetmagenta(0,0,null,null),
	carpetlblue(0,0,null,null),
	carpetyellow(0,0,null,null),
	carpetlgreen(0,0,null,null),
	carpetpink(0,0,null,null),
	carpetgray(0,0,null,null),
	carpetlgray(0,0,null,null),
	carpetcyan(0,0,null,null),
	carpetpurple(0,0,null,null),
	carpetblue(0,0,null,null),
	carpetbrown(0,0,null,null),
	carpetgreen(0,0,null,null),
	carpetred(0,0,null,null),
	carpetblack(0,0,null,null),
	hardenedclay(0,0,null,null),
	coalblock(0,0,null,null),
	
	//Items
	ironshovel(0,0,null,null),
	ironpickaxe(0,0,null,null),
	ironaxe(0,0,null,null),
	flintandsteel(0,0,null,null),
	apple(0,0,null,null),
	bow(0,0,null,null),
	arrow(0,0,null,null),
	coal(0,0,null,null),
	charcoal(0,0,null,null),
	diamond(0,0,null,null),
	ironingot(0,0,null,null),
	goldingot(0,0,null,null),
	ironsword(0,0,null,null),
	woodsword(0,0,null,null),
	woodshovel(0,0,null,null),
	woodpickaxe(0,0,null,null),
	woodaxe(0,0,null,null),
	stonesword(0,0,null,null),
	stoneshovel(0,0,null,null),
	stonepickaxe(0,0,null,null),
	stoneaxe(0,0,null,null),
	diamondsword(0,0,null,null),
	diamondshovel(0,0,null,null),
	diamondpickaxe(0,0,null,null),
	diamondaxe(0,0,null,null),
	woodstick(0,0,null,null),
	woodbowl(0,0,null,null),
	mushsoup(0,0,null,null),
	goldsword(0,0,null,null),
	goldshovel(0,0,null,null),
	goldpickaxe(0,0,null,null),
	goldaxe(0,0,null,null),
	string(0,0,null,null),
	feather(0,0,null,null),
	gunpowder(0,0,null,null),
	woodhoe(0,0,null,null),
	stonehoe(0,0,null,null),
	ironhoe(0,0,null,null),
	diamondhoe(0,0,null,null),
	goldhoe(0,0,null,null),
	seed(0,0,null,null),
	wheat(0,0,null,null),
	bread(0,0,null,null),
	leathercap(0,0,null,null),
	leatherchest(0,0,null,null),
	leatherlegs(0,0,null,null),
	leatherboots(0,0,null,null),
	chaincap(0,0,null,null),
	chainchest(0,0,null,null),
	chainlegs(0,0,null,null),
	chainboots(0,0,null,null),
	ironcap(0,0,null,null),
	ironchest(0,0,null,null),
	ironlegs(0,0,null,null),
	ironboots(0,0,null,null),
	diamondcap(0,0,null,null),
	diamondchest(0,0,null,null),
	diamondlegs(0,0,null,null),
	diamondboots(0,0,null,null),
	goldcap(0,0,null,null),
	goldchest(0,0,null,null),
	goldlegs(0,0,null,null),
	goldboots(0,0,null,null),
	flint(0,0,null,null),
	rawpork(0,0,null,null),
	cookpork(0,0,null,null),
	paint(0,0,null,null),
	goldapple1(0,0,null,null),
	goldapple2(0,0,null,null),
	sign(0,0,null,null),
	wooddoor(0,0,null,null),
	ironbucket(0,0,null,null),
	waterironbucket(0,0,null,null),
	lavaironbucket(0,0,null,null),
	minecart(0,0,null,null),
	saddle(0,0,null,null),
	irondoor(0,0,null,null),
	redstone(0,0,null,null),
	snowball(0,0,null,null),
	boat(0,0,null,null),
	leather(0,0,null,null),
	milkironbucket(0,0,null,null),
	brick(0,0,null,null),
	clay(0,0,null,null),
	sugarcane(0,0,null,null),
	paper(0,0,null,null),
	book(0,0,null,null),
	slimeball(0,0,null,null),
	chestminecart(0,0,null,null),
	furnaceminecart(0,0,null,null),
	egg(0,0,null,null),
	compass(0,0,null,null),
	fishingrod(0,0,null,null),
	clock(0,0,null,null),
	glowpowder(0,0,null,null),
	rawfish(0,0,null,null),
	cookfish(0,0,null,null),
	inksac(0,0,null,null),
	reddye(0,0,null,null),
	greendye(0,0,null,null),
	browndye(0,0,null,null),
	bluedye(0,0,null,null),
	purpledye(0,0,null,null),
	cyandye(0,0,null,null),
	lgreydye(0,0,null,null),
	greydye(0,0,null,null),
	pinkdye(0,0,null,null),
	lgreendye(0,0,null,null),
	yellowdye(0,0,null,null),
	lbluedye(0,0,null,null),
	magentadye(0,0,null,null),
	orangedye(0,0,null,null),
	whitedye(0,0,null,null),
	bone(0,0,null,null),
	sugar(0,0,null,null),
	cake(0,0,null,null),
	bed(0,0,null,null),
	repeater(0,0,null,null),
	cookie(0,0,null,null),
	map(0,0,null,null),
	shears(0,0,null,null),
	melonslice(0,0,null,null),
	pumpkinseed(0,0,null,null),
	melonseed(0,0,null,null),
	rawbeef(0,0,null,null),
	cookbeef(0,0,null,null),
	
	//Potions
	
	;
	
	private int id;
	private int meta;
	private String name;
	private EItemCat category;
	
	private EItem(int id, int meta, String name, EItemCat category) {
		this.id = id;
		this.meta = meta;
		this.name = name;
		this.category = category;
	}

	public int getId() {
		return id;
	}

	public int getMeta() {
		return meta;
	}

	public String getName() {
		return name;
	}

	public EItemCat getCategory() {
		return category;
	}
	
	public ArrayList<EItem> getByCategory(EItemCat category) {
		EItem[] values = values();
		ArrayList<EItem> items = new ArrayList<>();
		
		for(int i=0;i<values.length;i++) {
			EItem item = values[i];
			if(item.getCategory()==category){
				items.add(item);
			}
			
		}
		
		return null;
	}
	
}
