package model.enums;

public enum EMonsterAliases {
	zombie(EMonsters.zombie), 
	zombies(EMonsters.zombie),
	skeleton(EMonsters.skeleton),
	skeletons(EMonsters.skeleton),
	spider(EMonsters.spider),
	spiders(EMonsters.spider),
	creeper(EMonsters.creeper),
	creepers(EMonsters.creeper),
	wolf(EMonsters.wolf),
	wolves(EMonsters.wolf),
	zombie_pigman(EMonsters.zombie_pigman),
	zombie_pigmen(EMonsters.zombie_pigman),
	powered_creeper(EMonsters.powered_creeper),
	powered_creepers(EMonsters.powered_creeper),
	angry_wolf(EMonsters.angry_wolf),
	angry_wolves(EMonsters.angry_wolf),
	giant(EMonsters.giant),
	giants(EMonsters.giant),
	ghast(EMonsters.ghast),
	ghasts(EMonsters.ghast),
	enderman(EMonsters.enderman),
	endermen(EMonsters.enderman),
	silverfish(EMonsters.silverfish),
	cave_spider(EMonsters.cave_spider),
	cave_spiders(EMonsters.cave_spider),
	blaze(EMonsters.blaze),
	blazes(EMonsters.blaze),
	snowman(EMonsters.snowman),
	snowmen(EMonsters.snowman),
	snow_golem(EMonsters.snowman),
	snow_golems(EMonsters.snowman),
	iron_golem(EMonsters.iron_golem),
	iron_golems(EMonsters.iron_golem),
	witch(EMonsters.witch),
	witches(EMonsters.witch),
	wither(EMonsters.wither),
	withers(EMonsters.wither),
	wither_skeleton(EMonsters.wither_skeleton),
	wither_skeletons(EMonsters.wither_skeleton),
	baby_zombie(EMonsters.baby_zombie),
	baby_zombies(EMonsters.baby_zombie),
	baby_pigman(EMonsters.baby_pigman),
	baby_pigmen(EMonsters.baby_pigman),
	zombie_villager(EMonsters.zombie_villager),
	zombie_villagers(EMonsters.zombie_villager),
	chicken(EMonsters.chicken),
	chickens(EMonsters.chicken),
	cow(EMonsters.cow),
	cows(EMonsters.cow),
	mushroom_cow(EMonsters.mushroom_cow),
	mushroom_cows(EMonsters.mushroom_cow),
	pig(EMonsters.pig),
	pigs(EMonsters.pig),
	sheep(EMonsters.sheep),
	squid(EMonsters.squid),
	squids(EMonsters.squid),
	villager(EMonsters.villager),
	villagers(EMonsters.villager),
	ocelot(EMonsters.ocelot),
	ocelots(EMonsters.ocelot),
	bat(EMonsters.bat),
	bats(EMonsters.bat),
	exploding_sheep(EMonsters.exploding_sheep),
	slime(EMonsters.slime),
	slimes(EMonsters.slime),
	slime_tiny(EMonsters.slime_tiny),
	slimes_tiny(EMonsters.slime_tiny),
	slime_small(EMonsters.slime_small),
	slimes_small(EMonsters.slime_small),
	slime_big(EMonsters.slime_big),
	slimes_big(EMonsters.slime_big),
	slime_huge(EMonsters.slime_huge),
	slimes_huge(EMonsters.slime_huge),
	magmacube(EMonsters.magmacube),
	magmacubes(EMonsters.magmacube),
	magmacube_tiny(EMonsters.magmacube_tiny),
	magmacubes_tiny(EMonsters.magmacube_tiny),
	magmacube_small(EMonsters.magmacube_small),
	magmacubes_small(EMonsters.magmacube_small),
	magmacube_big(EMonsters.magmacube_big),
	magmacubes_big(EMonsters.magmacube_big),
	magmacube_huge(EMonsters.magmacube_huge),
	magmacubes_huge(EMonsters.magmacube_huge);
	
	private EMonsters monstre;

	EMonsterAliases(EMonsters monstre){
		this.monstre = monstre;
	}

	public EMonsters getMonstre() {
		return monstre;
	}
}
