# MobArena v0.95.5 - Config-file
# Read the Wiki for details on how to set up this file: http://goo.gl/F5TTc
# Note: You -must- use spaces instead of tabs!
global-settings:
    enabled: true
    allowed-commands: /list, /pl
    update-notification: true
classes:
    Knight:
        items: diamond_sword, potion:8197:3
        armor: 306,307,308,309
    Tank:
        items: iron_sword, potion:8229:2
        armor: 310,311,312,313
    Archer:
        items: wood_sword, bow, arrow:256, potion:8197:3, bone
        armor: 298,299,300,301
    Chemist:
        items: stone_sword, potion:16428:30, potion:16388:8, potion:16389:20, potion:8197:3, potion:8226:1
        armor: 314,315,316,317
    Oddjob:
        items: stone_sword, flint_and_steel, netherrack:2, tnt:4, potion:8197:3
        armor: 298,299,300,301
arenas:
    default:
        settings:
            world: world
            enabled: true
            protect: true
            entry-fee: ''
            clear-wave-before-next: false
            clear-boss-before-next: false
            clear-wave-before-boss: false
            lightning: true
            auto-equip-armor: true
            soft-restore: false
            soft-restore-drops: false
            require-empty-inv-join: false
            require-empty-inv-spec: false
            hellhounds: false
            pvp-enabled: false
            monster-infight: false
            allow-teleporting: false
            spectate-on-death: true
            auto-respawn: true
            share-items-in-arena: true
            min-players: 0
            max-players: 0
            max-join-distance: 0
            first-wave-delay: 5
            wave-interval: 15
            final-wave: 0
            monster-limit: 100
            monster-exp: false
            keep-exp: true
            food-regen: false
            lock-food-level: true
            spout-class-select: false
            player-time-in-arena: world
            auto-ignite-tnt: false
            auto-start-timer: 0
            use-class-chests: false
            display-waves-as-level: false
        waves:
            recurrent:
                def1:
                    type: default
                    priority: 1
                    frequency: 1
                    monsters:
                        zombies: 10
                        skeletons: 4
                        exploding_sheep: 5
                def2:
                    type: default
                    priority: 2
                    frequency: 1
                    wave: 5
                    monsters:
                        zombies: 10
                        skeletons: 6
                        creepers: 4
                spec1:
                    type: special
                    priority: 5
                    frequency: 4
                    wave: 4
                    monsters:
                        powered_creepers: 10
                        angry_wolves: 10
                        zombie_pigmen: 10
                upgrade1:
                    type: upgrade
                    priority: 7
                    frequency: 10
                    wave: 10
                    upgrades:
                        all: potion:8197:2
                        Archer: arrow:64
                        Oddjob: tnt:2, netherrack
                    give-all-items: true
            single:
                swarm1:
                    type: swarm
                    wave: 7
                    monster: slimes
                    amount: medium
                boss1:
                    type: boss
                    wave: 9
                    monster: spider
                    health: medium
                    abilities: fire-aura, disorient-target, fireballs, throw-nearby
                    ability-interval: 5
                boss2:
                    type: boss
                    wave: 13
                    monster: zombie_pigman
                    health: high
                    abilities: root-target, arrows, fire-aura
                upgrade2:
                    type: upgrade
                    wave: 14
                    upgrades:
                        all: potion:8197:2
                        Knight:
                            armor: diamond_helmet
                            items: diamond_sword 16:2;19:1
                        Tank:
                            items: iron_sword 19:3
                        Oddjob:
                            armor: iron_chestplate, iron_leggings
                        Wizard:
                            permissions:
                            - magicspells.cast.ChainLightning
                    give-all-items: true
                boss3:
                    type: boss
                    wave: 16
                    monster: wolf
                    health: psycho
                    abilities: warp-to-player, fire-aura, throw-nearby, fireballs, arrows
                    ability-interval: 1
                    reward: diamond_chestplate
                supply1:
                    type: supply
                    wave: 19
                    monsters:
                        cows: 10
                        pigs: 5
                    drops: grilled_pork, cooked_chicken, cooked_beef, cooked_fish:2
        rewards:
            waves:
                every:
                    '3': feather, bone, stick
                    '5': dirt:4, gravel:4, stone:4
                    '10': iron_ingot:10, gold_ingot:8
                after:
                    '7': minecart, storage_minecart, powered_minecart
                    '13': iron_sword, iron_pickaxe, iron_spade
                    '16': diamond_sword
        class-limits:
            Archer: -1
            Oddjob: -1
            Chemist: -1
            Tank: -1
            Knight: -1